# Generated by Django 4.2.7 on 2023-11-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0002_alter_cafe_close_time_alter_cafe_coffee_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='location',
            field=models.URLField(max_length=500),
        ),
    ]
